### ISSUE TITLE
ArrayIndexOutOfBoundsException when ortholog group not included in input-file exists in pattern-file

### ISSUE THREAD

**Issue by y-naka** [dinasv/CSBFinder#3]
I got following ArrayIndexOutOfBoundsException error when ortholog group not included in input-file exists in pattern-file.

```bash
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at Model.Genomes.Alphabet.getLetter(Alphabet.java:39)
	at Model.Genomes.GenomesInfo.getLetter(GenomesInfo.java:59)
	at Model.SuffixTreePatternFinder.SuffixTreeAlgorithm.appendChar(SuffixTreeAlgorithm.java:229)
	at Model.SuffixTreePatternFinder.SuffixTreeAlgorithm.extendPattern(SuffixTreeAlgorithm.java:395)
	at Model.SuffixTreePatternFinder.SuffixTreeAlgorithm.spellPatterns(SuffixTreeAlgorithm.java:264)
	at Model.SuffixTreePatternFinder.SuffixTreeAlgorithm.extendPattern(SuffixTreeAlgorithm.java:428)
	at Model.SuffixTreePatternFinder.SuffixTreeAlgorithm.spellPatterns(SuffixTreeAlgorithm.java:264)
	at Model.SuffixTreePatternFinder.SuffixTreeAlgorithm.findPatterns(SuffixTreeAlgorithm.java:153)
	at Model.CSBFinderWorkflow.run(CSBFinderWorkflow.java:73)
	at Model.Controller.pipeline(Controller.java:168)
	at Model.Controller.run(Controller.java:65)
	at Model.Controller.<init>(Controller.java:53)
	at MVC.Runnable.main(Runnable.java:12)
```

- Command
```bash
java -Xmx10g -jar CSBFinder-0.5.1-jar-with-dependencies.jar \
	-in ./test_in.fasta \
	-p ./test_pattern.fasta \
	-out TXT  \
	-q 1 \
	-out-dir ./test_out
```

- Input files

test_in.fasta
```
>A|B
a	+
b	+
c	+
d	+
e	+
```

test_pattern.fasta
```
>1
x,y,z
```

**Comment by dinasv** [comment]
Will be fixed in the next release

**Comment by dinasv** [comment]
Should be fixed
